all : 
	cd utils; \
	$(MAKE) all
	cd tools; \
	$(MAKE) all
	cd clients; \
	$(MAKE) all
	cd storprovider; \
	$(MAKE) all
	cd storserv; \
	$(MAKE) all
	cd vbi; \
	$(MAKE) all
	cd utest; \
	$(MAKE) all

clean : 
	cd utils; \
	$(MAKE) clean
	cd tools; \
	$(MAKE) clean
	cd clients; \
	$(MAKE) clean
	cd storprovider; \
	$(MAKE) clean
	cd storserv; \
	$(MAKE) clean
	cd vbi; \
	$(MAKE) clean
	cd utest; \
	$(MAKE) clean

depends : 
	cd utils; \
	$(MAKE) depends
	cd tools; \
	$(MAKE) depends
	cd storprovider; \
	$(MAKE) depends
	cd storserv; \
	$(MAKE) depends
	cd vbi; \
	$(MAKE) depends
	cd utest; \
	$(MAKE) depends

rmdepends :
	cd utils; \
	$(MAKE) rmdepends
	cd tools; \
	$(MAKE) rmdepends
	cd storprovider; \
	$(MAKE) rmdepends
	cd storserv; \
	$(MAKE) rmdepends
	cd vbi; \
	$(MAKE) rmdepends
	cd utest ; \
	$(MAKE) rmdepends
