REFERENCES := utils tools/boost/filesystem tools/boost/thread tools/cppunit storprovider storserv/fs tools/FUSE vbi
MYINCS := -I $(SYGHOME)/code/tools
MYLIBS := -ldl
include $(SYGHOME)/code/make/makefile
