#!/bin/sh

HERE=`pwd`
PATH="$PATH:.:$HERE"
export PATH

run_test()
{
	echo "Running Test $1"
	$1

	if [ "$?" -ne 0 ] ; then
		echo "Test '$1' failed"
		return 1
	fi

	return 0
}

#make tests

utblockssetup.sh

cat $SYGHOME/code/utest/alltests | while read line
do
	utblocksclean.sh
	run_test $line
	STATUS=$?
	if [ $STATUS -eq 1 ] ; then
		echo "Unit test run FAILED"
		exit 1
	fi
done

utblocksreset.sh

exit 0

