
#ifndef __BLOCKSTATUS_INCLUDE_
#define __BLOCKSTATUS_INCLUDE_

#define BSTATUS_SUCCESS		-2
#define BSTATUS_WRITEFAIL	-3
#define BSTATUS_MIRRORFAIL	-4
#define BSTATUS_READFAIL	-5
#define BSTATUS_MIRRORNOSPACE	-6
#define BSTATUS_WRITENOSPACE	-7

#endif /* __BLOCKSTATUS_INCLUDE_ */
